# Generated by Django 5.2.8 on 2025-11-29 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox"),
                            ("todo", "To Do"),
                            ("scheduled", "Scheduled"),
                            ("done", "Done"),
                            ("waiting", "Waiting"),
                            ("blocked", "Blocked"),
                            ("delegated", "Delegated"),
                            ("postponed", "Postponed"),
                            ("paused", "Paused"),
                            ("overdue", "Overdue"),
                        ],
                        default="inbox",
                        max_length=20,
                    ),
                ),
                ("duration_min", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_max", models.PositiveIntegerField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("is_fixed_time", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=3)),
                ("energy_required", models.IntegerField(default=2)),
                ("complexity", models.IntegerField(default=1)),
                ("is_private", models.BooleanField(default=False)),
                ("percent_complete", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
