# Generated by Django 5.2.8 on 2025-12-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_recurringpattern_task_recurring_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="review_date",
            field=models.DateField(
                blank=True, help_text="Kiedy przypomnieć o tym zadaniu?", null=True
            ),
        ),
    ]
