# Generated by Django 5.2.8 on 2025-12-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        ("tasks", "0008_checklistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="areas.area",
            ),
        ),
    ]
