# Generated by Django 5.2.8 on 2025-12-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_task_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_milestone",
            field=models.BooleanField(
                default=False, help_text="Oznacza punkt kontrolny projektu"
            ),
        ),
    ]
