# Generated by Django 5.2.8 on 2025-12-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_goal_parent"),
        ("tasks", "0010_task_is_milestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="goals.goal",
            ),
        ),
    ]
