# Generated by Django 5.2.8 on 2025-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_checklistitem_recurring_pattern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
