# Generated by Django 5.2.8 on 2025-12-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Postęp w procentach (0-100)"
            ),
        ),
    ]
