# Generated by Django 5.2.8 on 2025-12-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0001_initial"),
        ("goals", "0003_goal_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="areas.area",
            ),
        ),
    ]
