# Generated by Django 5.2.8 on 2025-12-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("projects", "0002_project_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="contexts.tag"
            ),
        ),
    ]
