# Generated by Django 5.2.8 on 2025-12-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktywny"),
                    ("completed", "Ukończony"),
                    ("on_hold", "Wstrzymany"),
                    ("archived", "Zarchiwizowany"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
