# Generated by Django 5.2.8 on 2025-12-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_wip_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_strategy",
            field=models.CharField(
                choices=[
                    ("balanced", "Zrównoważony"),
                    ("warmup", "Rozgrzewka (Proste/Krótkie)"),
                    ("deep_work", "Głęboka Praca (Projekt)"),
                    ("deadline", "Tryb Awaryjny (Terminy)"),
                ],
                default="balanced",
                max_length=20,
            ),
        ),
    ]
