# Generated by Django 5.2.8 on 2025-11-29 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_start_hour", models.TimeField(default="09:00")),
                ("work_end_hour", models.TimeField(default="17:00")),
                ("personal_start_hour", models.TimeField(default="17:00")),
                ("personal_end_hour", models.TimeField(default="22:00")),
                ("morning_buffer_minutes", models.PositiveIntegerField(default=30)),
                (
                    "between_tasks_buffer_minutes",
                    models.PositiveIntegerField(default=5),
                ),
                ("evening_buffer_minutes", models.PositiveIntegerField(default=30)),
                ("energy_profile", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
