# Generated by Django 5.2.8 on 2025-12-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_googlecredentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="wip_limit",
            field=models.PositiveIntegerField(
                default=5, help_text="Maksymalna liczba zadań w toku"
            ),
        ),
    ]
