# Generated by Django 5.2.8 on 2025-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="blocked_by",
            field=models.ManyToManyField(
                blank=True, related_name="blocking", to="tasks.task"
            ),
        ),
    ]
