# Generated by Django 5.2.8 on 2025-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_blocked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_critical_path",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("inbox", "Inbox"),
                    ("todo", "To Do"),
                    ("scheduled", "Scheduled"),
                    ("done", "Done"),
                    ("waiting", "Waiting"),
                    ("blocked", "Blocked"),
                    ("delegated", "Delegated"),
                    ("postponed", "Postponed"),
                    ("paused", "Paused"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                ],
                default="inbox",
                max_length=20,
            ),
        ),
    ]
