# Generated by Django 5.2.8 on 2025-11-30 21:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("tasks", "0004_task_is_critical_path_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Sztywny (Kalendarzowy)"),
                            ("dynamic", "Dynamiczny (Po wykonaniu)"),
                        ],
                        default="fixed",
                        max_length=10,
                    ),
                ),
                ("interval_days", models.PositiveIntegerField(default=7)),
                ("next_run_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("default_priority", models.IntegerField(default=3)),
                ("default_duration_min", models.IntegerField(default=30)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="recurring_pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_tasks",
                to="tasks.recurringpattern",
            ),
        ),
    ]
