# Generated by Django 5.2.8 on 2025-12-01 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contexts", "0001_initial"),
        ("tasks", "0006_task_review_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="contexts.context",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="contexts.tag"
            ),
        ),
    ]
