# Generated by Django 5.2.8 on 2025-12-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_task_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ready_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Kiedy zadanie stało się wykonalne (TODO/SCHEDULED)",
                null=True,
            ),
        ),
    ]
