# Generated by Django 5.2.8 on 2025-12-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_task_ready_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringpattern",
            name="completed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recurringpattern",
            name="generated_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
