# Generated by Django 5.2.8 on 2025-12-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_recurringpattern_completed_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringpattern",
            name="interval_days",
        ),
        migrations.RemoveField(
            model_name="recurringpattern",
            name="recurrence_type",
        ),
        migrations.AddField(
            model_name="recurringpattern",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recurringpattern",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Codziennie"),
                    ("WEEKLY", "Co tydzień"),
                    ("MONTHLY", "Co miesiąc"),
                    ("YEARLY", "Co rok"),
                ],
                default="WEEKLY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recurringpattern",
            name="interval",
            field=models.PositiveIntegerField(
                default=1, help_text="Co ile? (np. co 2 tygodnie)"
            ),
        ),
        migrations.AddField(
            model_name="recurringpattern",
            name="is_dynamic",
            field=models.BooleanField(
                default=False, help_text="Czy generować po wykonaniu poprzedniego?"
            ),
        ),
        migrations.AddField(
            model_name="recurringpattern",
            name="max_occurrences",
            field=models.PositiveIntegerField(
                blank=True, help_text="Zakończ po X wystąpieniach", null=True
            ),
        ),
        migrations.AddField(
            model_name="recurringpattern",
            name="week_days",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
