# Generated by Django 5.2.8 on 2025-12-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_remove_recurringpattern_interval_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="recurring_pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_items",
                to="tasks.recurringpattern",
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="tasks.task",
            ),
        ),
    ]
