# Generated by Django 5.2.8 on 2025-12-13 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_goal_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subgoals",
                to="goals.goal",
            ),
        ),
    ]
